/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTypesIndexRouteImport } from './routes/_authenticated/types/index'
import { Route as AuthenticatedTechnologiesIndexRouteImport } from './routes/_authenticated/technologies/index'
import { Route as AuthenticatedSubjectsIndexRouteImport } from './routes/_authenticated/subjects/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedRolesIndexRouteImport } from './routes/_authenticated/roles/index'
import { Route as AuthenticatedProfilesIndexRouteImport } from './routes/_authenticated/profiles/index'
import { Route as AuthenticatedEmailLogsIndexRouteImport } from './routes/_authenticated/email-logs/index'
import { Route as AuthenticatedDurationsIndexRouteImport } from './routes/_authenticated/durations/index'
import { Route as AuthenticatedDegreesIndexRouteImport } from './routes/_authenticated/degrees/index'
import { Route as AuthenticatedCandidaturesIndexRouteImport } from './routes/_authenticated/candidatures/index'
import { Route as AuthenticatedAuditsIndexRouteImport } from './routes/_authenticated/audits/index'
import { Route as AuthenticatedSettingsTypesRouteImport } from './routes/_authenticated/settings/types'
import { Route as AuthenticatedSettingsTechnologiesRouteImport } from './routes/_authenticated/settings/technologies'
import { Route as AuthenticatedSettingsProfilesRouteImport } from './routes/_authenticated/settings/profiles'
import { Route as AuthenticatedSettingsMailConfigRouteImport } from './routes/_authenticated/settings/mail-config'
import { Route as AuthenticatedSettingsFrontOfficeRouteImport } from './routes/_authenticated/settings/front-office'
import { Route as AuthenticatedSettingsEmailTemplatesRouteImport } from './routes/_authenticated/settings/email-templates'
import { Route as AuthenticatedSettingsDurationsRouteImport } from './routes/_authenticated/settings/durations'
import { Route as AuthenticatedSettingsDegreesRouteImport } from './routes/_authenticated/settings/degrees'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTypesIndexRoute = AuthenticatedTypesIndexRouteImport.update({
  id: '/types/',
  path: '/types/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTechnologiesIndexRoute =
  AuthenticatedTechnologiesIndexRouteImport.update({
    id: '/technologies/',
    path: '/technologies/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubjectsIndexRoute =
  AuthenticatedSubjectsIndexRouteImport.update({
    id: '/subjects/',
    path: '/subjects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedRolesIndexRoute = AuthenticatedRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfilesIndexRoute =
  AuthenticatedProfilesIndexRouteImport.update({
    id: '/profiles/',
    path: '/profiles/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmailLogsIndexRoute =
  AuthenticatedEmailLogsIndexRouteImport.update({
    id: '/email-logs/',
    path: '/email-logs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDurationsIndexRoute =
  AuthenticatedDurationsIndexRouteImport.update({
    id: '/durations/',
    path: '/durations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDegreesIndexRoute =
  AuthenticatedDegreesIndexRouteImport.update({
    id: '/degrees/',
    path: '/degrees/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCandidaturesIndexRoute =
  AuthenticatedCandidaturesIndexRouteImport.update({
    id: '/candidatures/',
    path: '/candidatures/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditsIndexRoute =
  AuthenticatedAuditsIndexRouteImport.update({
    id: '/audits/',
    path: '/audits/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsTypesRoute =
  AuthenticatedSettingsTypesRouteImport.update({
    id: '/types',
    path: '/types',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsTechnologiesRoute =
  AuthenticatedSettingsTechnologiesRouteImport.update({
    id: '/technologies',
    path: '/technologies',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsProfilesRoute =
  AuthenticatedSettingsProfilesRouteImport.update({
    id: '/profiles',
    path: '/profiles',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsMailConfigRoute =
  AuthenticatedSettingsMailConfigRouteImport.update({
    id: '/mail-config',
    path: '/mail-config',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsFrontOfficeRoute =
  AuthenticatedSettingsFrontOfficeRouteImport.update({
    id: '/front-office',
    path: '/front-office',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsEmailTemplatesRoute =
  AuthenticatedSettingsEmailTemplatesRouteImport.update({
    id: '/email-templates',
    path: '/email-templates',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDurationsRoute =
  AuthenticatedSettingsDurationsRouteImport.update({
    id: '/durations',
    path: '/durations',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDegreesRoute =
  AuthenticatedSettingsDegreesRouteImport.update({
    id: '/degrees',
    path: '/degrees',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/degrees': typeof AuthenticatedSettingsDegreesRoute
  '/settings/durations': typeof AuthenticatedSettingsDurationsRoute
  '/settings/email-templates': typeof AuthenticatedSettingsEmailTemplatesRoute
  '/settings/front-office': typeof AuthenticatedSettingsFrontOfficeRoute
  '/settings/mail-config': typeof AuthenticatedSettingsMailConfigRoute
  '/settings/profiles': typeof AuthenticatedSettingsProfilesRoute
  '/settings/technologies': typeof AuthenticatedSettingsTechnologiesRoute
  '/settings/types': typeof AuthenticatedSettingsTypesRoute
  '/audits/': typeof AuthenticatedAuditsIndexRoute
  '/candidatures/': typeof AuthenticatedCandidaturesIndexRoute
  '/degrees/': typeof AuthenticatedDegreesIndexRoute
  '/durations/': typeof AuthenticatedDurationsIndexRoute
  '/email-logs/': typeof AuthenticatedEmailLogsIndexRoute
  '/profiles/': typeof AuthenticatedProfilesIndexRoute
  '/roles/': typeof AuthenticatedRolesIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/subjects/': typeof AuthenticatedSubjectsIndexRoute
  '/technologies/': typeof AuthenticatedTechnologiesIndexRoute
  '/types/': typeof AuthenticatedTypesIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/degrees': typeof AuthenticatedSettingsDegreesRoute
  '/settings/durations': typeof AuthenticatedSettingsDurationsRoute
  '/settings/email-templates': typeof AuthenticatedSettingsEmailTemplatesRoute
  '/settings/front-office': typeof AuthenticatedSettingsFrontOfficeRoute
  '/settings/mail-config': typeof AuthenticatedSettingsMailConfigRoute
  '/settings/profiles': typeof AuthenticatedSettingsProfilesRoute
  '/settings/technologies': typeof AuthenticatedSettingsTechnologiesRoute
  '/settings/types': typeof AuthenticatedSettingsTypesRoute
  '/audits': typeof AuthenticatedAuditsIndexRoute
  '/candidatures': typeof AuthenticatedCandidaturesIndexRoute
  '/degrees': typeof AuthenticatedDegreesIndexRoute
  '/durations': typeof AuthenticatedDurationsIndexRoute
  '/email-logs': typeof AuthenticatedEmailLogsIndexRoute
  '/profiles': typeof AuthenticatedProfilesIndexRoute
  '/roles': typeof AuthenticatedRolesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/subjects': typeof AuthenticatedSubjectsIndexRoute
  '/technologies': typeof AuthenticatedTechnologiesIndexRoute
  '/types': typeof AuthenticatedTypesIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/settings/degrees': typeof AuthenticatedSettingsDegreesRoute
  '/_authenticated/settings/durations': typeof AuthenticatedSettingsDurationsRoute
  '/_authenticated/settings/email-templates': typeof AuthenticatedSettingsEmailTemplatesRoute
  '/_authenticated/settings/front-office': typeof AuthenticatedSettingsFrontOfficeRoute
  '/_authenticated/settings/mail-config': typeof AuthenticatedSettingsMailConfigRoute
  '/_authenticated/settings/profiles': typeof AuthenticatedSettingsProfilesRoute
  '/_authenticated/settings/technologies': typeof AuthenticatedSettingsTechnologiesRoute
  '/_authenticated/settings/types': typeof AuthenticatedSettingsTypesRoute
  '/_authenticated/audits/': typeof AuthenticatedAuditsIndexRoute
  '/_authenticated/candidatures/': typeof AuthenticatedCandidaturesIndexRoute
  '/_authenticated/degrees/': typeof AuthenticatedDegreesIndexRoute
  '/_authenticated/durations/': typeof AuthenticatedDurationsIndexRoute
  '/_authenticated/email-logs/': typeof AuthenticatedEmailLogsIndexRoute
  '/_authenticated/profiles/': typeof AuthenticatedProfilesIndexRoute
  '/_authenticated/roles/': typeof AuthenticatedRolesIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/subjects/': typeof AuthenticatedSubjectsIndexRoute
  '/_authenticated/technologies/': typeof AuthenticatedTechnologiesIndexRoute
  '/_authenticated/types/': typeof AuthenticatedTypesIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/errors/$error'
    | '/settings/degrees'
    | '/settings/durations'
    | '/settings/email-templates'
    | '/settings/front-office'
    | '/settings/mail-config'
    | '/settings/profiles'
    | '/settings/technologies'
    | '/settings/types'
    | '/audits/'
    | '/candidatures/'
    | '/degrees/'
    | '/durations/'
    | '/email-logs/'
    | '/profiles/'
    | '/roles/'
    | '/settings/'
    | '/subjects/'
    | '/technologies/'
    | '/types/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/errors/$error'
    | '/settings/degrees'
    | '/settings/durations'
    | '/settings/email-templates'
    | '/settings/front-office'
    | '/settings/mail-config'
    | '/settings/profiles'
    | '/settings/technologies'
    | '/settings/types'
    | '/audits'
    | '/candidatures'
    | '/degrees'
    | '/durations'
    | '/email-logs'
    | '/profiles'
    | '/roles'
    | '/settings'
    | '/subjects'
    | '/technologies'
    | '/types'
    | '/users'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/errors/$error'
    | '/_authenticated/settings/degrees'
    | '/_authenticated/settings/durations'
    | '/_authenticated/settings/email-templates'
    | '/_authenticated/settings/front-office'
    | '/_authenticated/settings/mail-config'
    | '/_authenticated/settings/profiles'
    | '/_authenticated/settings/technologies'
    | '/_authenticated/settings/types'
    | '/_authenticated/audits/'
    | '/_authenticated/candidatures/'
    | '/_authenticated/degrees/'
    | '/_authenticated/durations/'
    | '/_authenticated/email-logs/'
    | '/_authenticated/profiles/'
    | '/_authenticated/roles/'
    | '/_authenticated/settings/'
    | '/_authenticated/subjects/'
    | '/_authenticated/technologies/'
    | '/_authenticated/types/'
    | '/_authenticated/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/types/': {
      id: '/_authenticated/types/'
      path: '/types'
      fullPath: '/types/'
      preLoaderRoute: typeof AuthenticatedTypesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/technologies/': {
      id: '/_authenticated/technologies/'
      path: '/technologies'
      fullPath: '/technologies/'
      preLoaderRoute: typeof AuthenticatedTechnologiesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subjects/': {
      id: '/_authenticated/subjects/'
      path: '/subjects'
      fullPath: '/subjects/'
      preLoaderRoute: typeof AuthenticatedSubjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/roles/': {
      id: '/_authenticated/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof AuthenticatedRolesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profiles/': {
      id: '/_authenticated/profiles/'
      path: '/profiles'
      fullPath: '/profiles/'
      preLoaderRoute: typeof AuthenticatedProfilesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/email-logs/': {
      id: '/_authenticated/email-logs/'
      path: '/email-logs'
      fullPath: '/email-logs/'
      preLoaderRoute: typeof AuthenticatedEmailLogsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/durations/': {
      id: '/_authenticated/durations/'
      path: '/durations'
      fullPath: '/durations/'
      preLoaderRoute: typeof AuthenticatedDurationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/degrees/': {
      id: '/_authenticated/degrees/'
      path: '/degrees'
      fullPath: '/degrees/'
      preLoaderRoute: typeof AuthenticatedDegreesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidatures/': {
      id: '/_authenticated/candidatures/'
      path: '/candidatures'
      fullPath: '/candidatures/'
      preLoaderRoute: typeof AuthenticatedCandidaturesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audits/': {
      id: '/_authenticated/audits/'
      path: '/audits'
      fullPath: '/audits/'
      preLoaderRoute: typeof AuthenticatedAuditsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/types': {
      id: '/_authenticated/settings/types'
      path: '/types'
      fullPath: '/settings/types'
      preLoaderRoute: typeof AuthenticatedSettingsTypesRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/technologies': {
      id: '/_authenticated/settings/technologies'
      path: '/technologies'
      fullPath: '/settings/technologies'
      preLoaderRoute: typeof AuthenticatedSettingsTechnologiesRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/profiles': {
      id: '/_authenticated/settings/profiles'
      path: '/profiles'
      fullPath: '/settings/profiles'
      preLoaderRoute: typeof AuthenticatedSettingsProfilesRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/mail-config': {
      id: '/_authenticated/settings/mail-config'
      path: '/mail-config'
      fullPath: '/settings/mail-config'
      preLoaderRoute: typeof AuthenticatedSettingsMailConfigRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/front-office': {
      id: '/_authenticated/settings/front-office'
      path: '/front-office'
      fullPath: '/settings/front-office'
      preLoaderRoute: typeof AuthenticatedSettingsFrontOfficeRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/email-templates': {
      id: '/_authenticated/settings/email-templates'
      path: '/email-templates'
      fullPath: '/settings/email-templates'
      preLoaderRoute: typeof AuthenticatedSettingsEmailTemplatesRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/durations': {
      id: '/_authenticated/settings/durations'
      path: '/durations'
      fullPath: '/settings/durations'
      preLoaderRoute: typeof AuthenticatedSettingsDurationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/degrees': {
      id: '/_authenticated/settings/degrees'
      path: '/degrees'
      fullPath: '/settings/degrees'
      preLoaderRoute: typeof AuthenticatedSettingsDegreesRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsDegreesRoute: typeof AuthenticatedSettingsDegreesRoute
  AuthenticatedSettingsDurationsRoute: typeof AuthenticatedSettingsDurationsRoute
  AuthenticatedSettingsEmailTemplatesRoute: typeof AuthenticatedSettingsEmailTemplatesRoute
  AuthenticatedSettingsFrontOfficeRoute: typeof AuthenticatedSettingsFrontOfficeRoute
  AuthenticatedSettingsMailConfigRoute: typeof AuthenticatedSettingsMailConfigRoute
  AuthenticatedSettingsProfilesRoute: typeof AuthenticatedSettingsProfilesRoute
  AuthenticatedSettingsTechnologiesRoute: typeof AuthenticatedSettingsTechnologiesRoute
  AuthenticatedSettingsTypesRoute: typeof AuthenticatedSettingsTypesRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsDegreesRoute: AuthenticatedSettingsDegreesRoute,
    AuthenticatedSettingsDurationsRoute: AuthenticatedSettingsDurationsRoute,
    AuthenticatedSettingsEmailTemplatesRoute:
      AuthenticatedSettingsEmailTemplatesRoute,
    AuthenticatedSettingsFrontOfficeRoute:
      AuthenticatedSettingsFrontOfficeRoute,
    AuthenticatedSettingsMailConfigRoute: AuthenticatedSettingsMailConfigRoute,
    AuthenticatedSettingsProfilesRoute: AuthenticatedSettingsProfilesRoute,
    AuthenticatedSettingsTechnologiesRoute:
      AuthenticatedSettingsTechnologiesRoute,
    AuthenticatedSettingsTypesRoute: AuthenticatedSettingsTypesRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedAuditsIndexRoute: typeof AuthenticatedAuditsIndexRoute
  AuthenticatedCandidaturesIndexRoute: typeof AuthenticatedCandidaturesIndexRoute
  AuthenticatedDegreesIndexRoute: typeof AuthenticatedDegreesIndexRoute
  AuthenticatedDurationsIndexRoute: typeof AuthenticatedDurationsIndexRoute
  AuthenticatedEmailLogsIndexRoute: typeof AuthenticatedEmailLogsIndexRoute
  AuthenticatedProfilesIndexRoute: typeof AuthenticatedProfilesIndexRoute
  AuthenticatedRolesIndexRoute: typeof AuthenticatedRolesIndexRoute
  AuthenticatedSubjectsIndexRoute: typeof AuthenticatedSubjectsIndexRoute
  AuthenticatedTechnologiesIndexRoute: typeof AuthenticatedTechnologiesIndexRoute
  AuthenticatedTypesIndexRoute: typeof AuthenticatedTypesIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedAuditsIndexRoute: AuthenticatedAuditsIndexRoute,
  AuthenticatedCandidaturesIndexRoute: AuthenticatedCandidaturesIndexRoute,
  AuthenticatedDegreesIndexRoute: AuthenticatedDegreesIndexRoute,
  AuthenticatedDurationsIndexRoute: AuthenticatedDurationsIndexRoute,
  AuthenticatedEmailLogsIndexRoute: AuthenticatedEmailLogsIndexRoute,
  AuthenticatedProfilesIndexRoute: AuthenticatedProfilesIndexRoute,
  AuthenticatedRolesIndexRoute: AuthenticatedRolesIndexRoute,
  AuthenticatedSubjectsIndexRoute: AuthenticatedSubjectsIndexRoute,
  AuthenticatedTechnologiesIndexRoute: AuthenticatedTechnologiesIndexRoute,
  AuthenticatedTypesIndexRoute: AuthenticatedTypesIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
