export const TUNISIAN_UNIVERSITIES = [
  "Ecole Nationale d'Ingénieurs de Bizerte",
  "Ecole Nationale d'Ingénieurs de Carthage",
  "Ecole Nationale d'Ingénieurs de Gabès",
  "Ecole Nationale d'Ingénieurs de Gafsa",
  "Ecole Nationale d'Ingénieurs de Monastir",
  "Ecole Nationale d'Ingénieurs de Sfax",
  "Ecole Nationale d'Ingénieurs de Sousse",
  "Ecole Nationale d'Ingénieurs de Tunis",
  "Ecole Nationale des Sciences de l'Informatique",
  "Ecole Nationale des Sciences et Technologies Avancées de Borj Cédria",
  "Ecole Nationale d'Electronique et des Télécommunications de Sfax",
  "Ecole Nationale Supérieure d'Ingénieurs de Tunis",
  "Ecole Polytechnique de Tunisie",
  "Ecole Supérieure de Commerce de Tunis",
  "Ecole Supérieure d'Economie Numérique",
  "Ecole Supérieure des Ingénieurs de Medjez El Bab",
  "Ecole Supérieure des Sciences Economiques et Commerciales de Tunis",
  "Ecole Supérieure des Sciences et Technologies du Design",
  "Ecole Supérieure des Sciences et des Technologies de Hammam Sousse",
  "Ecole Supérieure des Sciences et Techniques de la Santé de Tunis",
  "Ecole Supérieure des Statistiques et d'Analyse de l'Information",
  "Faculté des Sciences de Bizerte",
  "Faculté des Sciences de Gabès",
  "Faculté des Sciences de Gafsa",
  "Faculté des Sciences de Monastir",
  "Faculté des Sciences de Sfax",
  "Faculté des Sciences Economiques et de Gestion de Mahdia",
  "Faculté des Sciences Economiques et de Gestion de Sfax",
  "Faculté des Sciences Economiques et de Gestion de Sousse",
  "Faculté des Sciences Economiques et de Gestion de Tunis",
  "Institut des Hautes Etudes Commerciales de Carthage",
  "Institut des Hautes Etudes Commerciales de Sfax",
  "Institut des Hautes Etudes Commerciales de Sousse",
  "Institut National des Sciences Appliquées et de Technologie de Tunis",
  "Institut National des Technologies et des Sciences du Kef",
  "Institut Préparatoire aux Etudes d'Ingénieurs d'El Manar",
  "Institut Préparatoire aux Etudes d'Ingénieurs de Bizerte",
  "Institut Préparatoire aux Etudes d'Ingénieurs de Gafsa",
  "Institut Préparatoire aux Etudes d'Ingénieurs de Kairouan",
  "Institut Préparatoire aux Etudes d'Ingénieurs de Monastir",
  "Institut Préparatoire aux Etudes d'Ingénieurs de Nabeul",
  "Institut Préparatoire aux Etudes d'Ingénieurs de Sfax",
  "Institut Préparatoire aux Etudes d'Ingénieurs de Tunis",
  "Institut Préparatoire aux Etudes Littéraires et des Sciences Humaines de Tunis",
  "Institut Préparatoire aux Etudes Scientifiques et techniques",
  "Institut Supérieur d'Administration des Entreprises de Gafsa",
  "Institut Supérieur d'Informatique",
  "Institut Supérieur d'Informatique de Mahdia",
  "Institut Supérieur d'Informatique de Medenine",
  "Institut Supérieur d'Informatique et de Gestion de Kairouan",
  "Institut Supérieur d'Informatique et de Mathématiques de Monastir",
  "Institut Supérieur d'Informatique et de Multimédia de Gabès",
  "Institut Supérieur d'Informatique et de Multimédia de Sfax",
  "Institut Supérieur d'Informatique et des Technologies de Communication de Hammam Sousse",
  "Institut Supérieur de Comptabilité et d'Administration des Entreprises de Manouba",
  "Institut Supérieur de Finances et de Fiscalité de Sousse",
  "Institut Supérieur de Gestion de Bizerte",
  "Institut Supérieur de Gestion de Gabès",
  "Institut Supérieur de Gestion de Sousse",
  "Institut Supérieur de Gestion de Tunis",
  "Institut Supérieur de Gestion Industrielle de Sfax",
  "Institut Supérieur de l'Informatique du Kef",
  "Institut Supérieur de Pêche et d'Aquaculture de Bizerte",
  "Institut Supérieur des Beaux Arts de Nabeul",
  "Institut Supérieur des Cadres de l'Enfance Carthage Dermech",
  "Institut Supérieur des Etudes Préparatoires en Biologie et Géologie à Soukra",
  "Institut Supérieur des Etudes Technologiques de Béja",
  "Institut Supérieur des Etudes Technologiques de Bizerte",
  "Institut Supérieur des Etudes Technologiques de Charguia",
  "Institut Supérieur des Etudes Technologiques de Gabès",
  "Institut Supérieur des Etudes Technologiques de Gafsa",
  "Institut Supérieur des Etudes Technologiques de Jendouba",
  "Institut Supérieur des Etudes Technologiques de Jerba",
  "Institut Supérieur des Etudes Technologiques de Kairouan",
  "Institut Supérieur des Etudes Technologiques de Kasserine",
  "Institut Supérieur des Etudes Technologiques de Kebili",
  "Institut Supérieur des Etudes Technologiques de Kélibia",
  "Institut Supérieur des Etudes Technologiques de Ksar Hellal",
  "Institut Supérieur des Etudes Technologiques de Mahdia",
  "Institut Supérieur des Etudes Technologiques de Médenine",
  "Institut Supérieur des Etudes Technologiques de Nabeul",
  "Institut Supérieur des Etudes Technologiques de Rades",
  "Institut Supérieur des Etudes Technologiques de Sfax",
  "Institut Supérieur des Etudes Technologiques de Sidi Bouzid",
  "Institut Supérieur des Etudes Technologiques de Siliana",
  "Institut Supérieur des Etudes Technologiques de Sousse",
  "Institut Supérieur des Etudes Technologiques de Tataouine",
  "Institut Supérieur des Etudes Technologiques de Tozeur",
  "Institut Supérieur des Etudes Technologiques de Zaghouan",
  "Institut Supérieur des Etudes Technologiques du Kef",
  "Institut Supérieur des Etudes Technologiques en Communications de Tunis",
  "Institut Supérieur des Etudes Touristique de Sidi Dhrif",
  "Institut Supérieur des Mathématiques Appliquées et de l'Informatique de Kairouan",
  "Institut Supérieur des Sciences Appliquées et de la Technologie de Mateur",
  "Institut Supérieur des Sciences Appliquées et de Technologie de Gabès",
  "Institut Supérieur des Sciences Appliquées et de Technologie de Gafsa",
  "Institut Supérieur des Sciences Appliquées et de Technologie de Kairouan",
  "Institut Supérieur des Sciences Appliquées et de Technologie de Kasserine",
  "Institut Supérieur des Sciences Appliquées et de Technologie de Mahdia",
  "Institut Supérieur des Sciences Appliquées et de Technologie de Sousse",
  "Institut Supérieur des Sciences et Technologies de l'Environnement de Borj Cédria",
  "Institut Supérieur des Sciences et des Technologies de l'Energie de Gafsa",
  "Institut Supérieur des Technologies de l'Information et de la Communication",
  "Tunis Business School",

  // Private institutions
  "Ecole Centrale Supérieure Privée d'Informatique et de Communication de Tunis",
  "Ecole Internationale Supérieure Privée Polytechnique de Sousse",
  "Ecole Internationale Supérieure Privée Polytechnique de Tunis",
  "Ecole Méditerranéenne Supérieure Privée Polytechnique",
  "Ecole Polytechnique Internationale Supérieure Privée de Sfax",
  "Ecole Supérieure Internationale Privée de Technologie / Sfax",
  "Ecole Supérieure Internationale Privée de Tunis",
  "Ecole Supérieure Polytechnique Privée de Monastir",
  "Ecole Supérieure Polytechnique Privée de Sousse",
  "Ecole Supérieure Polytechnique Privée Ibn Khaldoun / Tunis",
  "Ecole Supérieure Privée Centrale Polytechnique / Tunis",
  "Ecole Supérieure Privée d'Ingénierie et de Technologie / Tunis",
  "Ecole Supérieure Privée d'Ingénierie, des Sciences et de Technologie de Sousse",
  "Ecole Supérieure Privée d'Ingénieurs de Gafsa",
  "Ecole Supérieure Privée d'Ingénieurs de Monastir",
  "Ecole Supérieure Privée d'Informatique et d'Administration des Affaires/Tunis",
  "Ecole Supérieure Privée d'Informatique et de Technologie",
  "Ecole Supérieure Privée d'Informatique et de Technologie de digitalisation",
  "Ecole Supérieure Privée de Carthage des Sciences et d'Ingénierie / Tunis",
  "Ecole Supérieure Privée de Technologie Avancée de Sousse",
  "Ecole Supérieure Privée de Technologie de l'Information et de Management de Nabeul",
  "Ecole Supérieure Privée de Technologie, d'Informatique et de Gestion de Sousse",
  "Ecole Supérieure Privée de Technologie et d'Ingénierie",
  "Ecole Supérieure Privée des Sciences Appliquées et de Technologie de Gabès",
  "Ecole Supérieure Privée Magrébine des Sciences et Technologie",
  "Ecole Supérieure Privée d'Ingénierie d'Informatique et d'Administration des Affaires",
  "Ecole Supérieure Privée d'Ingénieurs et d'Etudes Technologiques de Tunis",
  "Faculté Méditerranéenne Privée des Sciences Informatiques, d'Economie et de Gestion de Tunis",
  "Faculté Privée de Montplaisir / Tunis",
  "Faculté Privée des Sciences de Gestion et de Technologie à Mégrine / Tunis",
  "Faculté Privée des Sciences de l'Informatique et de Management de Nabeul",
  "Institut Privé des Hautes Etudes de Sousse",
  "Institut Privé des Hautes Etudes de Tunis",
  "Institut Supérieur Polytechnique Privé des Sciences Avancées du Sud",
  "Institut Supérieur Privé des Sciences et Technologie en Informatique Appliquée de Sousse",
  "Institut Supérieur Privé des Technologies de la Digitalisation",
  "Institut Supérieur Privé Méditerranéen de Technologie",
  "Institut Supérieur Privé Polytechnique/ Tunis",
  "Institut Supérieur Privé Tunis Dauphine/ Tunis",
] as const
