server {
    listen 80;

    location = /backoffice { return 301 /backoffice/; }

    location /backoffice/ {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /backoffice/index.html;
    }
}
